### ISSUE TITLE
Hostname of LXC is set to "LXCNAME"

### ISSUE THREAD

**Issue by mschabhuettl** [Jip-Hop/jailmaker#115] opened 2024-04-07 13:40 UTC
Hello!

I've just discovered that since v1.1.2, when you create a jail, the Hostname of the LXC is set to "LXCNAME" instead of the specified jail name.

jlmkr setup

```
root@NAS[~]# jlmkr create
USE THIS SCRIPT AT YOUR OWN RISK!
IT COMES WITHOUT WARRANTY AND IS NOT SUPPORTED BY IXSYSTEMS.

Do you wish to create a jail from a config template? [y/N] 

Install the recommended image (debian bookworm)? [Y/n] 

Enter jail name: nextcloud

Docker won't be installed by jlmkr.py.
But it can setup the jail with the capabilities required to run docker.
You can turn DOCKER_COMPATIBLE mode on/off post-install.

Make jail docker compatible right now? [y/N] y

Passthrough the intel GPU (if present)? [y/N] 

Passthrough the nvidia GPU (if present)? [y/N] 

WARNING: CHECK SYNTAX

You may pass additional flags to systemd-nspawn.
With incorrect flags the jail may not start.
It is possible to correct/add/remove flags post-install.

Show the man page for systemd-nspawn? [y/N] 

You may read the systemd-nspawn manual online:
https://manpages.debian.org/bookworm/systemd-container/systemd-nspawn.1.en.html

Would you like to add additional systemd-nspawn flags?
For example to mount directories inside the jail you may:
Mount the TrueNAS location /mnt/pool/dataset to the /home directory of the jail with:
--bind='/mnt/pool/dataset:/home'
Or the same, but readonly, with:
--bind-ro='/mnt/pool/dataset:/home'
Or create macvlan interface with:
--network-macvlan=eno1 --resolv-conf=bind-host

Additional flags: --bind='/mnt/tardis/jails/nextcloud/data:/mnt/nextcloud_data' --network-bridge=br12 --resolv-conf=bind-host

The `jlmkr.py startup` command can automatically ensure jlmkr.py is installed properly and start a selection of jails.
This comes in handy when you want to automatically start multiple jails after booting TrueNAS SCALE (e.g. from a Post Init Script).

Do you want to start this jail when running: jlmkr.py startup? [y/N] y

Do you want to start this jail now (when create is done)? [Y/n] 

Downloading the image index
Downloading the rootfs
Downloading the metadata
The image cache is now ready
Unpacking the rootfs

Starting jail nextcloud with the following command:

systemd-run --collect --property=Delegate=yes --property=RestartForceExitStatus=133 --property=SuccessExitStatus=133 --property=TasksMax=infinity --property=Type=notify --setenv=SYSTEMD_NSPAWN_LOCK=0 --property=KillMode=mixed --unit=jlmkr-nextcloud --working-directory=./jails/nextcloud '--description=My nspawn jail nextcloud [created with jailmaker]' --setenv=SYSTEMD_SECCOMP=0 --property=DevicePolicy=auto -- systemd-nspawn --bind-ro=/sys/module --boot --inaccessible=/sys/module/apparmor --quiet --keep-unit --machine=nextcloud --directory=rootfs --capability=all --bind=/mnt/tardis/jails/nextcloud/data:/mnt/nextcloud_data --network-bridge=br12 --resolv-conf=bind-host

Running as unit: jlmkr-nextcloud.service
```

via `machinectl shell nextcloud`:

```
root@NAS[~]# machinectl shell nextcloud
Connected to machine nextcloud. Press ^] three times within 1s to exit session.
root@LXCNAME:~# cat /etc/hostname
LXC_NAME
```

so: root@LXCNAME should be root@nextcloud, and LXC_NAME in /etc/hostname should also be nextcloud

Cheers,
Matthias

**Comment by Jip-Hop** [comment] 2024-04-07 13:53
Can you please double check that using v1.1.1 brings back the desired behavior? To rule out the cause of this is inside the image rootfs itself.

**Comment by mschabhuettl** [comment] 2024-04-07 13:55
I've used the script successfully yesterday in the evening. Today I reinstalled jlmkr and now it broke. That's what I can tell you right now.

**Comment by mschabhuettl** [comment] 2024-04-07 14:23
I haven't tested it, but could it be that the bug occurs due to the changes in commit [eee3abe](https://github.com/Jip-Hop/jailmaker/commit/eee3abef8e501212ffd6c754221c067ee97eff91)? I just had a quick look at your source code - I'm just conjecturing.

**Comment by Jip-Hop** [comment] 2024-04-07 14:29
Maybe unrelated but aren't you running into problems because of the dataset name? You have `/mnt/tardis/jails` but jailmaker requires the dataset to be named "jailmaker". Also see:

https://github.com/truenas/documentation/pull/2629

**Comment by mschabhuettl** [comment] 2024-04-07 14:36
@Jip-Hop unrelated /mnt/tardis/jails/nextcloud/data is the datadir for my nextcloud ai.
jailmaker jlmkr.py sits in /mnt/gallifrey/jailmaker/jlmkr.py

PS: yes i am a Dr. Who Fan

**Comment by mschabhuettl** [comment] 2024-04-07 14:42
Appendix: Just tested my suggestion in https://github.com/Jip-Hop/jailmaker/issues/115#issuecomment-2041487495 but this is not the issue.

I'v also tried to install a debian bullseye. Same issue.

**Comment by mschabhuettl** [comment] 2024-04-07 14:52
@Jip-Hop:

Reverting back to 1.1.1 did the trick:

```
root@NAS[/mnt/test/jailmaker]# jlmkr create
USE THIS SCRIPT AT YOUR OWN RISK!
IT COMES WITHOUT WARRANTY AND IS NOT SUPPORTED BY IXSYSTEMS.

Do you wish to create a jail from a config template? [y/N] 

Install the recommended image (debian bookworm)? [Y/n] 

Enter jail name: nextcloud

Docker won't be installed by jlmkr.py.
But it can setup the jail with the capabilities required to run docker.
You can turn DOCKER_COMPATIBLE mode on/off post-install.

Make jail docker compatible right now? [y/N] y

Passthrough the intel GPU (if present)? [y/N] 

Passthrough the nvidia GPU (if present)? [y/N] 

WARNING: CHECK SYNTAX

You may pass additional flags to systemd-nspawn.
With incorrect flags the jail may not start.
It is possible to correct/add/remove flags post-install.

Show the man page for systemd-nspawn? [y/N] 

You may read the systemd-nspawn manual online:
https://manpages.debian.org/bookworm/systemd-container/systemd-nspawn.1.en.html

Would you like to add additional systemd-nspawn flags?
For example to mount directories inside the jail you may:
Mount the TrueNAS location /mnt/pool/dataset to the /home directory of the jail with:
--bind='/mnt/pool/dataset:/home'
Or the same, but readonly, with:
--bind-ro='/mnt/pool/dataset:/home'
Or create macvlan interface with:
--network-macvlan=eno1 --resolv-conf=bind-host

Additional flags: 

The `jlmkr.py startup` command can automatically ensure jlmkr.py is installed properly and start a selection of jails.
This comes in handy when you want to automatically start multiple jails after booting TrueNAS SCALE (e.g. from a Post Init Script).

Do you want to start this jail when running: jlmkr.py startup? [y/N] y

Do you want to start this jail now (when create is done)? [Y/n] 

Using image from local cache
Unpacking the rootfs

---
You just created a Debian bookworm amd64 (20240407_05:24) container.

To enable SSH, run: apt install openssh-server
No default root or user password are set by LXC.

Starting jail nextcloud with the following command:

systemd-run --collect --property=Delegate=yes --property=RestartForceExitStatus=133 --property=SuccessExitStatus=133 --property=TasksMax=infinity --property=Type=notify --setenv=SYSTEMD_NSPAWN_LOCK=0 --property=KillMode=mixed --unit=jlmkr-nextcloud --working-directory=./jails/nextcloud '--description=My nspawn jail nextcloud [created with jailmaker]' --setenv=SYSTEMD_SECCOMP=0 --property=DevicePolicy=auto -- systemd-nspawn --bind-ro=/sys/module --boot --inaccessible=/sys/module/apparmor --quiet --keep-unit --machine=nextcloud --directory=rootfs --capability=all

Running as unit: jlmkr-nextcloud.service
root@NAS[/mnt/test/jailmaker]# machinectl shell nextcloud
Connected to machine nextcloud. Press ^] three times within 1s to exit session.
root@nextcloud:~#
```

**Comment by mschabhuettl** [comment] 2024-04-07 14:55
Issue has to be somewhere between 1.1.1 and 1.1.2 @Jip-Hop

**Comment by Jip-Hop** [comment] 2024-04-07 15:03
Thanks I'll look into it!

**Comment by mschabhuettl** [comment] 2024-04-07 15:07
@Jip-Hop just saw that in 949c162

at line 834 there was

```
remove_lines_after_line_number(lxc_download_script, 404)
```

added

I've taken a look at https://raw.githubusercontent.com/Jip-Hop/lxc/97f93be72ebf380f3966259410b70b1c966b0ff0/templates/lxc-download.in

And as i understand 'remove_lines_after_line_number'-function, it throws away everything after line 404.
Including

```
# Replace variables in all templates
OLD_IFS=${IFS}
IFS=";"
for file in ${TEMPLATE_FILES}; do
    [ ! -f "${file}" ] && continue
  sed -i "s#LXC_NAME#${LXC_NAME}#g" "${file}"
  sed -i "s#LXC_PATH#${LXC_PATH}#g" "${file}"
  sed -i "s#LXC_ROOTFS#${LXC_ROOTFS}#g" "${file}"
  sed -i "s#LXC_TEMPLATE_CONFIG#${LXC_TEMPLATE_CONFIG}#g" "${file}"
  sed -i "s#LXC_HOOK_DIR#${LXC_HOOK_DIR}#g" "${file}"
done
IFS=${OLD_IFS}
```

it seems LXC_NAME is set there. This might be the issue.

Cheers

**Comment by Jip-Hop** [comment] 2024-04-07 15:18
You're right. But v1.1.1 used this script: https://github.com/Jip-Hop/lxc/blob/665a5a0527ee7a10133fb0b438447ea4bc0e55e9/templates/lxc-download.in#L401

To which I added `exit` on line 401 which should be equivalent to throwing away the lines that follow...

So I'm still a bit confused what is causing this unfortunately xD But there have also been some chances to the `lxc-download.in` file itself so I may need to look at those again.

**Comment by mschabhuettl** [comment] 2024-04-07 15:40
@Jip-Hop Fix provided in PR #116.
Tested it and it works now!

```
root@NAS[/mnt/test/jailmaker]# jlmkr --version
1.1.3
root@NAS[/mnt/test/jailmaker]# machinectl shell nextcloud
Connected to machine nextcloud. Press ^] three times within 1s to exit session.
root@nextcloud:~# cat /etc/hostname 
nextcloud
root@nextcloud:~#
```

Cheers,
Matthias Schabhüttl

**Comment by mschabhuettl** [comment] 2024-04-07 16:31
@Jip-Hop you could merge my pull request to get a quick fix and take a look at optimizations later, as my code does not remove any features.

**Comment by Jip-Hop** [comment] 2024-04-07 16:52
Thanks! It's fixed now :)

https://github.com/Jip-Hop/jailmaker/releases/tag/v1.1.3

**Closed by Jip-Hop** 2024-04-07 16:52 UTC
