### ISSUE TITLE
Failed to allocate directory watch: Too many open files

### ISSUE THREAD

**Issue by SergeySevbitov** [Jip-Hop/jailmaker#35] opened 2023-09-24 03:16 UTC
I started an Ubuntu Jammy jail on TrueNAS Scale and tried to modify sshd service settings (port).
Upon restarting a service it threw an error:
```shell
systemctl restart sshd
Failed to allocate directory watch: Too many open files
```
Googling suggested increasing the limit by `ulimit -n ...`, but I suspect it does not address the root cause.

Could you please advise on this case?

Thanks.

**Comment by Jip-Hop** [comment] 2023-09-24 08:45
Looks like a duplicate of https://github.com/Jip-Hop/jailmaker/issues/31. Please try the suggested solution and report back :)

**Closed by Jip-Hop** 2023-09-24 08:45 UTC

**Comment by SergeySevbitov** [comment] 2023-09-24 09:27
> Looks like a duplicate of #31. Please try the suggested solution and report back :)

You are right, did not notice it, was confused by seeing no open issues there :rofl:
Anyway, the issue is solved, thank you.
