### ISSUE TITLE
intel_gpu_top: Operation not permitted

### ISSUE THREAD

**Issue by izenn** [Jip-Hop/jailmaker#168] opened 2024-05-11 00:26 UTC
**Describe the bug**
when i try to run intel_gpu_top i get an Operation not permitted error

**To Reproduce**
Create jail with docker template with the pass through intel gpu option enabled
```
apt-get install intel-gpu-tools
```
```
/usr/bin/intel_gpu_top
Failed to initialize PMU! (Operation not permitted)
```
```
setcap cap_perfmon=+ep /usr/bin/intel_gpu_top
```
```
/usr/bin/intel_gpu_top 
bash: /usr/bin/intel_gpu_top: Operation not permitted
```

**Expected behavior**
intel_gpu_top to return gpu data

**Jailmaker:**
1.4.0

**TrueNAS SCALE:**
Dragonfish-24.04.0

**Additional context**
GPU passthrough has been confirmed to work using jellyfin transcoding
if i run intel_gpu_top outside the jail (by navigating to the rootfs) it works.  
additionally, if i set any --capabilities (tested with CAP_PERFMON and all) the PMU error stays and the setcap does not change anything

**Comment by Jip-Hop** [comment] 2024-05-11 08:44
Seccomp is causing the "Operation not permitted" error. You should allow some more syscalls in addition to `--system-call-filter='add_key keyctl bpf'` which is already present in the docker jail. I don't know which ones but I can confirm running `intel_gpu_top` in the jails works when I disable seccomp. There should be no need to add additional capabilities. I'm closing this issue as this is not a bug.

**Comment by izenn** [comment] 2024-05-11 23:49
for documentation, intel_gpu_top requires perf_event_open to be added to the system-call-filter. this was determined by running:
```
# strace /usr/bin/intel_gpu_top 2>&1 |grep Operation\ not\ permitted
perf_event_open({type=0x10 /* PERF_TYPE_??? */, size=PERF_ATTR_SIZE_VER7, config=0x100002, sample_period=0, sample_type=0, read_format=PERF_FORMAT_TOTAL_TIME_ENABLED|PERF_FORMAT_GROUP, precise_ip=0 /* arbitrary skid */, use_clockid=1, ...}, -1, 0, -1, 0) = -1 EPERM (Operation not permitted)
write(2, "Failed to initialize PMU! (Opera"..., 52Failed to initialize PMU! (Operation not permitted)
```
would it make sense to add something about using strace to find what system-call-filters may be needed so that disabling seccomp is more of a last resort?

**Comment by Jip-Hop** [comment] 2024-05-12 07:21
Good idea. Please provide a PR to update the docs. 😄

**Closed** 2024-05-13 06:13 UTC
Labels: documentation, help wanted
